directories:
  # Local folder
  model: ./output/models
  # Volume directory for data. /data-sunia-gpu/danielp/npi_data/binarization_128
  data: /home/daniel/nas_data/strokes_resnet_224

# DDP set-up, choosing GPUs to train with
visible_devices: [4, 5]
num_devices: 2

model:
  name: SE_EFFICIENTNET
  version: 6
  encoder: "efficientnet"
  # encoder_checkpoint:
  # decoder_checkpoint: ./output/models/SE_RESNET/models/SE_RESNET_04/SE_RESNET_04_decoder_020.pt

  parameters:
    encoded_image_size: 14 # Adaptive average pool to (14, 14)
    attention_dim: 512 # 512
    embed_dim: 512 # 512
    encoder_dim: 512
    decoder_dim: 512 # 512
    vocab_size: 451 # 224 + 224 + 3
    dropout: 0.5
  
  train:
    batch_size: 32
    num_workers: 8
    epochs: 25
    start_epoch: 0 # Start at this epoch in case training was disrupted.
    encoder_lr: 0.00001 # Base LR
    decoder_lr: 0.00004 # Base LR
    encoder_peak_lr: 0.0001
    decoder_peak_lr: 0.0004
    encoder_decay_lr: 0.00001 # Back to base LR
    decoder_decay_lr: 0.00004 # Back to base LR
    peak_epoch: 5 # Epoch at which the LR is highest.
    alpha_c: 1.0
    grad_clip: 5.0
    save_per_epoch: 1

dataset:
  train_batches:
    CN_pencil_001_010: [skeleton]
    CN_pencil_011_020: [skeleton]
    CN_pencil_021_030: [skeleton]
    CN_pencil_031_040: [skeleton]
    CN_pencil_041_050: [skeleton]
    CN_pencil_051_060: [skeleton]
    CN_pencil_061_070: [skeleton]
    CN_pencil_071_080: [skeleton]
    CN_pencil_081_090: [skeleton]
    CN_pencil_091_100: [skeleton]
    CN_pencil_101_110: [skeleton]
    CN_pencil_111_120: [skeleton]
    CN_pencil_121_130: [skeleton]
    CN_pencil_131_140: [skeleton]
    CN_pencil_141_150: [skeleton]
    CN_pencil_151_160: [skeleton]
    CN_pencil_161_170: [skeleton]
    CN_pencil_171_180: [skeleton]
    CN_pencil_181_190: [skeleton]
    CN_pencil_191_200: [skeleton]
    CN_pencil_201_210: [skeleton]
    CN_pencil_211_220: [skeleton]
    CN_pencil_221_230: [skeleton]
    CN_pencil_231_240: [skeleton]
    CN_pencil_241_250: [skeleton]
    CN_pencil_251_260: [skeleton]
    CN_pencil_261_270: [skeleton]
    CN_pencil_281_290: [skeleton]
    CN_pencil_291_300: [skeleton]
    CN_pencil_301_310: [skeleton]
    tanzil_chalk_1000: [skeleton]
    tanzil_chalk_2000: [skeleton]
    tanzil_chalk_3000: [skeleton]
    tanzil_chalk_4000: [skeleton]
    tanzil_chalk_5000: [skeleton]
    tanzil_chalk_6000: [skeleton]
    tanzil_chalk_7000: [skeleton]
    tanzil_chalk_8000: [skeleton]
    tanzil_chalk_9000: [skeleton]
    tanzil_chalk_10000: [skeleton]
    tanzil_chalk_11000: [skeleton]
    tanzil_pen_cil_1000: [skeleton]
    tanzil_pen_cil_2000: [skeleton]
    tanzil_pen_cil_3000: [skeleton]
    tanzil_pen_cil_4000: [skeleton]
    tanzil_pen_cil_5000: [skeleton]
    tanzil_pen_cil_6000: [skeleton]
    tanzil_pen_cil_7000: [skeleton]
    IAM_en_lines_00: [skeleton]
    IAM_en_lines_01: [skeleton]
    IAM_en_lines_02: [skeleton]
    IAM_en_lines_03: [skeleton]
    IAM_en_lines_04: [skeleton]
    IAM_en_lines_05: [skeleton]
    IAM_en_lines_06: [skeleton]
    IAM_en_lines_07: [skeleton]
    IAM_en_lines_08: [skeleton]
    IAM_en_lines_09: [skeleton]
    harbin_000: [skeleton]
    harbin_001: [skeleton]
    harbin_002: [skeleton]
    harbin_003: [skeleton]
    harbin_004: [skeleton]
    harbin_005: [skeleton]
    harbin_006: [skeleton]
    harbin_007: [skeleton]
    harbin_008: [skeleton]
    harbin_009: [skeleton]
    harbin_010: [skeleton]
    harbin_011: [skeleton]
    harbin_012: [skeleton]
    harbin_013: [skeleton]
    harbin_014: [skeleton]
    harbin_015: [skeleton]
    harbin_016: [skeleton]
    harbin_017: [skeleton]
    harbin_018: [skeleton]
    harbin_019: [skeleton]
    harbin_020: [skeleton]
    harbin_021: [skeleton]
    harbin_022: [skeleton]
    harbin_023: [skeleton]
    harbin_024: [skeleton]
    harbin_025: [skeleton]
    harbin_026: [skeleton]
    harbin_027: [skeleton]
    harbin_028: [skeleton]
    harbin_029: [skeleton]
    harbin_030: [skeleton]
    harbin_031: [skeleton]
    harbin_032: [skeleton]
    harbin_033: [skeleton]
    harbin_034: [skeleton]
    harbin_035: [skeleton]
    harbin_036: [skeleton]
    harbin_037: [skeleton]
    harbin_038: [skeleton]
    harbin_039: [skeleton]
    harbin_040: [skeleton]
    harbin_041: [skeleton]
    harbin_042: [skeleton]
    harbin_043: [skeleton]
    harbin_044: [skeleton]
    harbin_045: [skeleton]
    harbin_046: [skeleton]
    harbin_047: [skeleton]
    harbin_048: [skeleton]
    harbin_049: [skeleton]
    harbin_050: [skeleton]
    harbin_051: [skeleton]
    harbin_052: [skeleton]
    harbin_053: [skeleton]
    harbin_054: [skeleton]
    harbin_055: [skeleton]
    harbin_056: [skeleton]
    harbin_057: [skeleton]
    harbin_058: [skeleton]
    harbin_059: [skeleton]
    harbin_060: [skeleton]
    harbin_061: [skeleton]
    harbin_062: [skeleton]
    harbin_063: [skeleton]
    harbin_064: [skeleton]
    harbin_065: [skeleton]
    harbin_066: [skeleton]
    harbin_067: [skeleton]
    harbin_068: [skeleton]
    harbin_069: [skeleton]
    harbin_070: [skeleton]
    harbin_071: [skeleton]
    harbin_072: [skeleton]
    harbin_073: [skeleton]
    harbin_074: [skeleton]
    harbin_075: [skeleton]
    harbin_076: [skeleton]
    harbin_077: [skeleton]
    harbin_078: [skeleton]
    harbin_079: [skeleton]

  val_batches:
    CN_pencil_311_320: [skeleton]
    CN_pencil_321_330: [skeleton]
    CN_pencil_331_340: [skeleton]
    CN_pencil_341_350: [skeleton]
    CN_pencil_351_360: [skeleton]
    CN_pencil_361_370: [skeleton]
    CN_pencil_371_380: [skeleton]
    CN_pencil_381_390: [skeleton]
    CN_pencil_391_400: [skeleton]
    tanzil_chalk_12000: [skeleton]
    tanzil_chalk_13000: [skeleton]
    tanzil_chalk_14000: [skeleton]
    tanzil_chalk_15000: [skeleton]
    tanzil_pen_cil_8000: [skeleton]
    tanzil_pen_cil_9000: [skeleton]
    tanzil_pen_cil_10000: [skeleton]
    IAM_en_lines_10: [skeleton]
    IAM_en_lines_11: [skeleton]
    harbin_080: [skeleton]
    harbin_081: [skeleton]
    harbin_082: [skeleton]
    harbin_083: [skeleton]
    harbin_084: [skeleton]
    harbin_085: [skeleton]
    harbin_086: [skeleton]
    harbin_087: [skeleton]
    harbin_088: [skeleton]
    harbin_089: [skeleton]
    harbin_090: [skeleton]
    harbin_091: [skeleton]
    harbin_092: [skeleton]
    harbin_093: [skeleton]
    harbin_094: [skeleton]
    harbin_095: [skeleton]
    harbin_096: [skeleton]
    harbin_097: [skeleton]
    harbin_098: [skeleton]
    harbin_099: [skeleton]